name: java ci here

on: [push, pull_request]

jobs:

  Maven_run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  run_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Run Test
        run: mvn -pl typescript-generator-core test -Dtest="cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces"
                
  run_test_with_nondex:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
        
      - name: Run Test w nondex
        run: mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest='cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces'
